// essentials-react/src/components/ShippingCarriersSection.jsx
import React from 'react';
import SectionTitle from './SectionTitle';
import AnimatedSection from './AnimatedSection';
import { Truck, Package, Clock, Shield, MapPin, CheckCircle } from 'lucide-react';

const ShippingCarriersSection = () => {
  const carriers = [
    {
      name: 'USPS',
      logo: '/images/carriers/usps.png',
      description: 'Reliable nationwide delivery with competitive rates and comprehensive tracking.',
      features: [
        { icon: <Package size={16} />, text: 'Priority Mail' },
        { icon: <Clock size={16} />, text: '1-3 Business Days' },
        { icon: <Shield size={16} />, text: 'Insurance Available' }
      ]
    },
    {
      name: 'UPS',
      logo: '/images/carriers/ups.png',
      description: 'Premium shipping services with guaranteed delivery times and advanced logistics.',
      features: [
        { icon: <Truck size={16} />, text: 'Ground & Air' },
        { icon: <MapPin size={16} />, text: 'Real-time Tracking' },
        { icon: <CheckCircle size={16} />, text: 'Guaranteed Delivery' }
      ]
    },
    {
      name: 'FedEx',
      logo: '/images/carriers/fedex.png',
      description: 'Express delivery solutions with real-time tracking and signature confirmation.',
      features: [
        { icon: <Clock size={16} />, text: 'Overnight Available' },
        { icon: <Shield size={16} />, text: 'Signature Required' },
        { icon: <Package size={16} />, text: 'Express Services' }
      ]
    },
    {
      name: 'DHL',
      logo: '/images/carriers/dhl.png',
      description: 'International shipping expertise with global reach and customs handling.',
      features: [
        { icon: <MapPin size={16} />, text: 'Global Network' },
        { icon: <Truck size={16} />, text: 'Customs Handling' },
        { icon: <CheckCircle size={16} />, text: 'International Express' }
      ]
    }
  ];

  return (
    <section className="shipping-carriers">
      <div className="container">
        <SectionTitle 
          title="Shipping Carriers We Support" 
          subtitle="Reliable delivery through trusted partners" 
        />
        
        <div className="text-banner">
          <div className="text-banner-content">
            <span>USPS</span>
            <span>•</span>
            <span>UPS</span>
            <span>•</span>
            <span>FEDEX</span>
            <span>•</span>
            <span>DHL</span>
            <span>•</span>
            <span>USPS</span>
            <span>•</span>
            <span>UPS</span>
            <span>•</span>
            <span>FEDEX</span>
            <span>•</span>
            <span>DHL</span>
          </div>
        </div>
        
        <div className="marquee-container">
          <div className="marquee">
            {[...carriers, ...carriers].map((carrier, index) => (
              <AnimatedSection 
                key={`${carrier.name}-${index}`} 
                className="carrier-item"
                delay={`${index * 100}`}
              >
                <div className="carrier-logo-small">
                  <img 
                    src={carrier.logo} 
                    alt={`${carrier.name} logo`} 
                  />
                </div>
                <h3>{carrier.name}</h3>
              </AnimatedSection>
            ))}
          </div>
        </div>
        
        <div className="carriers-grid">
          {carriers.map((carrier, index) => (
            <AnimatedSection 
              key={carrier.name} 
              className="carrier-card"
              delay={`${index * 150}`}
            >
              <div className="carrier-logo">
                <img src={carrier.logo} alt={`${carrier.name} logo`} className="animated-carrier-logo" />
              </div>
              <h3>{carrier.name}</h3>
              <p>{carrier.description}</p>
              <div className="carrier-features">
                {carrier.features.map((feature, featureIndex) => (
                  <div key={featureIndex} className="feature-item">
                    <span className="feature-icon">{feature.icon}</span>
                    <span className="feature-text">{feature.text}</span>
                  </div>
                ))}
              </div>
            </AnimatedSection>
          ))}
        </div>
      </div>
    </section>
  );
};

export default ShippingCarriersSection;

// essentials-nuxt/components/ShippingCarriersSection.tsx
export default defineComponent({
  name: 'ShippingCarriersSection',
  render() {
    return (
      <section class="py-20 bg-gradient-to-b from-gray-50 to-white">
        <div class="container mx-auto px-6">
          <SectionTitle 
            title="Shipping Carriers" 
            subtitle="We partner with trusted carriers for reliable delivery"
          />
          <div class="grid md:grid-cols-4 gap-8 max-w-5xl mx-auto">
            <AnimatedSection delay={100}>
              <div class="bg-white rounded-2xl p-8 shadow-lg text-center border border-gray-100 hover:shadow-xl transition-all duration-300 hover:scale-105">
                <div class="h-16 flex items-center justify-center mx-auto mb-6">
                  <img src="/images/carriers/ups.png" alt="UPS" class="h-20 object-contain" />
                </div>
                <h3 class="text-xl font-bold mb-2 text-gray-800">UPS</h3>
                <p class="text-gray-600">Fast and reliable ground shipping</p>
              </div>
            </AnimatedSection>
            
            <AnimatedSection delay={200}>
              <div class="bg-white rounded-2xl p-8 shadow-lg text-center border border-gray-100 hover:shadow-xl transition-all duration-300 hover:scale-105">
                <div class="h-16 flex items-center justify-center mx-auto mb-6">
                  <img src="/images/carriers/fedex.png" alt="FedEx" class="h-20 object-contain" />
                </div>
                <h3 class="text-xl font-bold mb-2 text-gray-800">FedEx</h3>
                <p class="text-gray-600">Express delivery worldwide</p>
              </div>
            </AnimatedSection>
            
            <AnimatedSection delay={300}>
              <div class="bg-white rounded-2xl p-8 shadow-lg text-center border border-gray-100 hover:shadow-xl transition-all duration-300 hover:scale-105">
                <div class="h-16 flex items-center justify-center mx-auto mb-6">
                  <img src="/images/carriers/usps.png" alt="USPS" class="h-20 object-contain" />
                </div>
                <h3 class="text-xl font-bold mb-2 text-gray-800">USPS</h3>
                <p class="text-gray-600">Cost-effective postal services</p>
              </div>
            </AnimatedSection>
            
            <AnimatedSection delay={400}>
              <div class="bg-white rounded-2xl p-8 shadow-lg text-center border border-gray-100 hover:shadow-xl transition-all duration-300 hover:scale-105">
                <div class="h-16 flex items-center justify-center mx-auto mb-6">
                  <img src="/images/carriers/dhl.png" alt="DHL" class="h-20 object-contain" />
                </div>
                <h3 class="text-xl font-bold mb-2 text-gray-800">DHL</h3>
                <p class="text-gray-600">International express delivery</p>
              </div>
            </AnimatedSection>
          </div>
        </div>
      </section>
    )
  }
})
