// essentials-nuxt/components/SectionTitle.tsx
interface Props {
  title: string
  subtitle?: string
  className?: string
}

export default defineComponent({
  name: 'SectionTitle',
  props: {
    title: {
      type: String,
      required: true
    },
    subtitle: {
      type: String,
      default: ''
    },
    className: {
      type: String,
      default: ''
    }
  },
  setup(props: Props) {
    return {
      ...props
    }
  },
  render() {
    return (
      <div class={`text-center mb-16 ${this.className}`}>
        <h2 class="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
          <span class="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
            {this.title}
          </span>
        </h2>
        {this.subtitle && (
          <p class="text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed">
            {this.subtitle}
          </p>
        )}
      </div>
    )
  }
})

// essentials-react/src/components/SectionTitle.jsx
import React from 'react';

const SectionTitle = ({ title, subtitle, className = '' }) => {
  return (
    <div className={`text-center mb-16 ${className}`}>
      <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
        <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
          {title}
        </span>
      </h2>
      {subtitle && (
        <p className="text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed">
          {subtitle}
        </p>
      )}
    </div>
  );
};

export default SectionTitle;
